"""empty message

Revision ID: 464c55df02a8
Revises: 4f378f39a3ba
Create Date: 2025-04-11 20:44:58.413932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '464c55df02a8'
down_revision: Union[str, None] = '4f378f39a3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploaded_files', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'done', 'failed', 'cancelled', name='filestatus'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploaded_files', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'processing', 'done', 'failed', 'cancelled', name='filestatus'),
               existing_nullable=True)
    # ### end Alembic commands ###
