"""empty message

Revision ID: 4f378f39a3ba
Revises: c4328272dd01
Create Date: 2025-04-09 21:18:06.060095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f378f39a3ba'
down_revision: Union[str, None] = 'c4328272dd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('status', sa.Enum('processing', 'done', 'failed', name='filestatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_files', 'status')
    # ### end Alembic commands ###
